### ISSUE TITLE
BUG: git-fat script is not included in the package.

### ISSUE THREAD

**Issue by musically-ut** [data-workspaces/data-workspaces-core#34]
Doing a fresh install of the package from the source and trying to use `git-fat` reveals that the `git-fat` file in `third_party/` folder is not included in the package by default. This problem does not happen while running from the source.

```
$ git-fat
Traceback (most recent call last):
  File "/home/.../miniconda3/bin/git-fat", line 10, in <module>
    sys.exit(main())
  File "/home/.../miniconda3/lib/python3.7/site-packages/dataworkspaces/third_party/git_fat.py", line 79, in main
    run_git_fat(python2, args)
  File "/home/.../miniconda3/lib/python3.7/site-packages/dataworkspaces/third_party/git_fat.py", line 60, in run_git_fat
    raise InternalError("Missing %s" % fat_script)
dataworkspaces.errors.InternalError: Missing /home/.../miniconda3/lib/python3.7/site-packages/dataworkspaces/third_party/git-fat
```

This happens because `git-fat` lacks the `.py` suffix.

The solution is either to include the file explicitly as `data` in `setup.py`:

```python
package_data={'': ['dataworkspaces/third_party/git-fat']},
include_package_data=True,
```

or by creating a `MANIFEST.in` file which includes it:

```
include dataworkspaces/third_party/git-fat
```

I personally prefer the latter approach.

**Comment by jfischer** [comment]
Thanks for your issue! I added the MANIFEST.in file as you suggested, bumped the version up to 1.0.5, and uploaded it to PyPI. It looks like it works, based on my testing. Please let me know if you run into any problems.
